### ISSUE TITLE
Difficulties recreating environment

### ISSUE THREAD

**Issue by hudson-ayers** [citp/TheWebNeverForgets#2]
Hi, I am attempting to rerun the parallel and serialized crawls in this repository, but am having a difficult time getting my python environment correct. I traced back the wiki in the OpenWPM repo to get the install instructions from that point in time, and used the setup.sh script in modcrawler, all run on a fresh Ubuntu 14.04 VM. But running either crawling script fails due to issues with libmproxy/mitmproxy as a result of changes in those dependencies since this code was originally written. I reverted mitmproxy to version 0.11.3, but this led to other issues with incompatibility with the cryptography library.

Do you happen to have either a VM image with the correct dependencies installed, or specific versions that work for each dependency? I saw a link to a VM image somewhere, but the link was dead.

Thanks!

**Comment by englehardt** [comment]
Unfortunately we no longer have the VM image available and I don't have all of the dependency versions saved from the time of this measurement. This is evidence that we could use better dependency management and should pin to specific versions in each release.

May I ask why you'd like to run crawls with such an outdated version of OpenWPM? If you'd like to reuse the analysis scripts you're better off running a modern version of the crawler and simply adapting them for schema changes. That way you'll have any bugfixes that have happened since 2014 and will be crawling with a more modern version of Firefox.

**Comment by hudson-ayers** [comment]
Mostly I wanted to run crawls on the outdated version because then I knew the analysis scripts would work out of the box, as well as the accompanying scripts for visualization of the collected data, which would let me quickly see some preliminary results, while if I use the more modern version of OpenWPM I will have to modify the crawl scripts to match the general collection behavior of the old crawl scripts as well as modify the analysis tools. Also, this paper used modCrawler for some of the analysis, and I will have to move all of that crawling over to OpenWPM. No worries though, I will work on adapting the scripts to work with the modern version of OpenWPM. Thanks for your response!

**Comment by hudson-ayers** [comment]
@englehardt one more question -- did you ever do a code release for any of your 2016 study on canvas fingerprinting? That code might be more useful alongside OpenWPM today. Thanks!
